### ISSUE TITLE
Declaration2 not used in the grammar

### ISSUE THREAD

**Issue by kingsleyh** [Hackerpilot/DGrammar#5]
Hi

Previously the grammar had:

declaration ::= attribute* declaration2;

but now it just has:

declaration ::= attribute*;

which means declaration2 is now unused??? This doesn't seem quite right to me?

**Comment by Hackerpilot** [comment]
You may have better luck reading the doc comments from the parser directly. I don't re-generate the HTML file in this project very often.

https://github.com/Hackerpilot/libdparse/blob/master/src/std/d/parser.d#L1741

**Comment by Hackerpilot** [comment]
Fixed in https://github.com/Hackerpilot/DGrammar/commit/fc55afcce625f41d3c33772057f182c3d0e27b52
