### ISSUE TITLE
AnonymousEnumMember missing from Grammar

### ISSUE THREAD

**Issue by kingsleyh** [Hackerpilot/DGrammar#6]
Hi,

AnonymousEnumDeclaration and its AnonymousEnumMember seems to be missing from the grammar.

http://dlang.org/enum.html#EnumBody

**Comment by Hackerpilot** [comment]
Fixed in https://github.com/Hackerpilot/DGrammar/commit/fc55afcce625f41d3c33772057f182c3d0e27b52
